---
- name: Installs nginx web server
  community.general.pkgng:
    name: nginx
    state: present
  become: yes

- name: Enable nginx
  ansible.builtin.command: sysrc nginx_enable="YES"
  become: yes

- name: Add text/x-rst mime type
  ansible.builtin.lineinfile:
    name: /usr/local/etc/nginx/mime.types
    line: '    text/x-rst                                      rst;'
    regexp: 'text/x-rst'
    insertbefore: '^}'
    state: present
  become: yes

- name: Add text/markdown mime type
  ansible.builtin.lineinfile:
    name: /usr/local/etc/nginx/mime.types
    line: '    text/markdown                                    md;'
    regexp: 'text/markdown'
    insertbefore: '^}'
    state: present
  become: yes

- name: Append to text/plain mime type
  ansible.builtin.lineinfile:
    name: /usr/local/etc/nginx/mime.types
    line: '    text/plain                                       txt log Dockerfile;'
    regexp: '    text/plain                                       txt'
    state: present
  become: yes

- name: create nginx conf.d dir
  ansible.builtin.file:
    path: /usr/local/etc/nginx/conf.d
    state: directory
    mode: 0755
    owner: root
    group: wheel
  become: yes

- name: copy nginx.conf template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: "u=rw,g=r,o=r"
    backup: yes
  register: nginx_conf_update
  become: yes

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
  when: nginx_conf_update.changed
  become: yes
