---
- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
  become: yes

# http://docutils.sourceforge.net/FAQ.html#what-s-the-official-mime-type-for-restructuredtext-data
- name: add text/x-rst mime type
  ansible.builtin.lineinfile:
    name: /etc/nginx/mime.types
    line: '    text/x-rst                                      rst;'
    regexp: 'text/x-rst'
    insertbefore: '^}'
    state: present
  become: yes

# http://docutils.sourceforge.net/FAQ.html#what-s-the-official-mime-type-for-restructuredtext-data
- name: add text/markdown mime type
  ansible.builtin.lineinfile:
    name: /etc/nginx/mime.types
    line: '    text/markdown                                    md;'
    regexp: 'text/markdown'
    insertbefore: '^}'
    state: present
  become: yes

- name: append to text/plain mime type
  ansible.builtin.lineinfile:
    name: /etc/nginx/mime.types
    line: '    text/plain                                       txt log Dockerfile;'
    regexp: '    text/plain                                       txt'
    state: present
  become: yes

- name: copy stub_status config
  ansible.builtin.copy:
    src: files/stub_status.conf
    dest: /etc/nginx/conf.d/stub_status.conf
    owner: root
    group: wheel
    mode: "u=rw,g=r,o=r"
    backup: yes
  register: nginx_conf_stub_status_update
  become: yes

- name: create directory /etc/systemd/system/nginx.service.d/
  ansible.builtin.file:
    path: /etc/systemd/system/nginx.service.d
    state: directory
    mode: 0755
    owner: root
    group: root
  become: yes

- name: copy systemd override.conf config
  ansible.builtin.copy:
    src: files/override.conf
    dest: /etc/systemd/system/nginx.service.d/override.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    backup: yes
  register: nginx_conf_systemd_override_conf_update
  when: ansible_service_mgr == "systemd"
  become: yes

- name: enable and start nginx service systemd
  systemd:
    name: nginx
    enabled: yes
    state: started
  when: ansible_service_mgr == "systemd"
  become: yes
