---
- name: Install Prometheus Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
  become: true

- name: Enable and start prometheus-node-exporter.service
  ansible.builtin.systemd:
    name: prometheus-node-exporter.service
    enabled: yes
    state: started
  become: true
