---
- name: create admin user
  ansible.builtin.user:
    name: "{{ admin_user }}"
    password: "{{ admin_password | password_hash('sha512', password_salt) }}"
    groups: sudo
    append: yes
  become: yes
