---
- name: installs certbot
  community.general.pkgng:
    name: py38-certbot
    state: present
  become: yes

- name: crontab set shell
  ansible.builtin.cron:
    name: SHELL
    env: yes
    value: /bin/sh
  become: yes

- name: crontab set path
  ansible.builtin.cron:
    name: PATH
    env: yes
    value: /etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
    insertafter: SHELL
  become: yes

- name: enable certbot renew cron job
  ansible.builtin.cron:
    name: certbot renew
    job: certbot renew --deploy-hook /usr/local/etc/letsencrypt/renewal-hooks/deploy/01-reload-nginx
    weekday: "{{ cron_weekday }}"
    hour: "{{ cron_hour }}"
    minute: "{{ cron_minute }}"
  become: yes
  when:
    - nginx == true

- name: create directory /usr/local/etc/newsyslog.conf.d/
  ansible.builtin.file:
    path: /usr/local/etc/newsyslog.conf.d/
    state: directory
    mode: 0755
    owner: root
    group: wheel
  become: yes

# https://www.freebsd.org/doc/handbook/configtuning-syslog.html
# https://www.freebsd.org/cgi/man.cgi?query=newsyslog.conf&sektion=5&manpath=freebsd-release-ports
- name: configure certbot log rotation
  ansible.builtin.copy:
    src: files/newsyslog.certbot.conf
    dest: /usr/local/etc/newsyslog.conf.d/certbot.conf
    owner: root
    group: wheel
    mode: 0644
  become: yes

- name: create directory /usr/local/etc/letsencrypt/renewal-hooks/deploy/
  ansible.builtin.file:
    path: /usr/local/etc/letsencrypt/renewal-hooks/deploy/
    state: directory
    mode: 0755
    owner: root
    group: wheel
  become: yes

# Sources:
# https://www.guyrutenberg.com/2017/01/01/lets-encrypt-reload-nginx-after-renewing-certificates/
# https://certbot.eff.org/docs/using.html#renewing-certificates
- name: configure certbot renewal hook to reload nginx
  ansible.builtin.copy:
    src: files/01-reload-nginx-freebsd
    dest: /usr/local/etc/letsencrypt/renewal-hooks/deploy/01-reload-nginx
    owner: root
    group: wheel
    mode: 0755
  become: yes
  when:
    - nginx == true
