---
# Add the rule twice
# Once to add to running config
- name: remove prometheus node exporter from public zone (online mode)
  command: "firewall-cmd --zone=public --remove-port=9100/tcp"
  when:
  - firewalld_running
  become: yes

- name: remove nginx prometheus exporter from public zone (online mode)
  command: "firewall-cmd --zone=public --remove-port=9113/tcp"
  when:
  - firewalld_running
  become: yes

# Second to add to make it permanent config and survive restart
- name: remove prometheus node exporter from public zone (permanent) (online mode)
  command: "firewall-cmd --permanent --zone=public --remove-port=9100/tcp"
  when:
  - firewalld_running
  become: yes

- name: remove nginx prometheus exporter from public zone (permanent) (online mode)
  command: "firewall-cmd --permanent --zone=public --remove-port=9113/tcp"
  when:
  - firewalld_running
  become: yes

- name: remove prometheus node exporter from public zone (offline mode)
  command: "firewall-offline-cmd --zone=public --remove-port-from-zone=9100/tcp"
  when:
  - not firewalld_running
  become: yes

- name: remove nginx prometheus exporter from public zone (offline mode)
  command: "firewall-offline-cmd --zone=public --remove-port-from-zone=9113/tcp"
  when:
  - not firewalld_running
  become: yes
