---
# Add the rule twice
# Once to add to running config
- name: remove ssh from public zone (online mode)
  command: "firewall-cmd --zone=public --remove-service=ssh"
  when:
  - firewalld_running
  become: yes

# Second to add to make it permanent config and survive restart
- name: remove ssh from public zone (permanent) (online mode)
  command: "firewall-cmd --permanent --zone=public --remove-service=ssh"
  when:
  - firewalld_running
  become: yes

- name: remove ssh from public zone (offline mode)
  command: "firewall-offline-cmd --zone=public --remove-service-from-zone=ssh"
  when:
  - not firewalld_running
  become: yes
