---
# Add the rule twice
# Once to add to running config
- name: enable http and https in public zone (online mode)
  command: "firewall-cmd --zone=public --add-service=http --add-service=https"
  when:
  - firewalld_running
  become: yes

# Second to add to make it permanent config and survive restart
- name: enable http and https in public zone (permanent) (online mode)
  command: "firewall-cmd --permanent --zone=public --add-service=http --add-service=https"
  when:
  - firewalld_running
  become: yes

- name: enable http and https in public zone (offline mode)
  command: "firewall-offline-cmd --zone=public --add-service-to-zone=http --add-service-to-zone=https"
  when:
  - not firewalld_running
  become: yes
