---
# https://docs.fedoraproject.org/en-US/epel/#_el8
- name: enable powertools
  command: dnf config-manager --set-enabled powertools
  when:
    - ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux"
  become: yes

- name: enable ol9_developer_EPEL
  command: dnf config-manager --set-enabled ol9_developer_EPEL
  when:
    - ansible_distribution == "OracleLinux"
  become: yes

- name: install epel-release
  ansible.builtin.dnf:
    name: epel-release
    state: present
  become: yes

- name: setup epel
  command: dnf update -y
  become: yes
