---
- name: remove customized PATH and JAVA_HOME from user profile
  blockinfile:
    path: "/home/{{ username }}/.profile"
    state: absent
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      if [ -d /usr/local/sdkman/candidates/java/current/bin ]; then
          PATH="/usr/local/sdkman/candidates/java/current/bin:$PATH"
          JAVA_HOME="/usr/local/sdkman/candidates/java/current"
      fi
  become: yes

# - name: remove agent jar

- name: remove jenkins ssh authorized keys
  file:
    name: "/etc/ssh/authorized_keys/{{ username }}"
    state: absent
  become: yes

- name: reconfigure sshd_config to remove path to authorizedkeys directive
  blockinfile:
    path: "/etc/ssh/sshd_config"
    state: absent
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      AuthorizedKeysFile /etc/ssh/authorized_keys/%u .ssh/authorized_keys /home/%u/.ssh/authorized_keys
  become: yes
  notify: restart sshd

- name: remove jenkins ssh user
  user:
    name: "{{ username }}"
    state: absent
    force: yes
  become: yes

- name: remove group jenkins
  group:
    name: "{{ username }}"
    state: absent
  become: yes

- name: remove JAVA_HOME environment variable system-wide
  lineinfile:
    path: /etc/environment
    state: absent
    regexp: "JAVA_HOME='/usr/local/sdkman/candidates/java/current'"
  become: yes

- name: remove sdkman directory
  file:
    name: /usr/local/sdkman
    state: absent
  become: yes

- name: remove sdkman installer
  file:
    name: /usr/local/bin/sdkman-installer.sh
    state: absent
  become: yes
